{% set name = "dexp" %}
{% set version = "2022.12.22.907" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3dfaa54c80b974a122b934b2d1b25b770911c58a728d06560d7692446d041d2

build:
  entry_points:
    - dexp=dexp.cli.dexp_main:cli
    - dexp-video=dexp.cli.video_main:cli
    - dexp-install=dexp.cli.install_main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - arbol
    - cachey
    - cairocffi
    - click >=8.0.0
    - colorcet
    - dask-core >=21.6.0
    - dask-cuda >=21.6.0
    - dask-image
    - distributed
    - gpustat
    - gputil
    - gputools
    - joblib
    - numba
    - numcodecs
    - numexpr
    - numpy >=1.20
    - ome-zarr
    - platformdirs
    - pyotf
    - pytest
    - python >=3.7
    - python-blosc
    - pyyaml
    - scikit-image
    - scipy
    - seaborn
    - tifffile
    - tqdm
    - zarr

test:
  imports:
    - dexp
  commands:
    - pip list
    # - pip check
    - dexp --help
    - dexp-video --help
    - dexp-install --help
  requires:
    - oclgrind
    - pip

about:
  home: https://github.com/royerlab/dexp
  summary: Light-sheet Dataset EXploration and Processing
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - JoOkuma
